import { Transaction } from "@/types";

export const mockTransactions: Transaction[] = [
  {
    id: "tx-1",
    date: "2024-03-20",
    amount: 1250.0,
    category: "Income",
    description: "Salary Payment",
    type: "income",
    status: "completed",
  },
  {
    id: "tx-2",
    date: "2024-03-19",
    amount: 45.2,
    category: "Food & Dining",
    description: "Starbucks Coffee",
    type: "expense",
    status: "completed",
  },
  {
    id: "tx-3",
    date: "2024-03-18",
    amount: 120.0,
    category: "Transportation",
    description: "Uber Ride",
    type: "expense",
    status: "completed",
  },
  {
    id: "tx-4",
    date: "2024-03-17",
    amount: 350.0,
    category: "Rent",
    description: "Monthly Rent Contribution",
    type: "expense",
    status: "completed",
  },
  {
    id: "tx-5",
    date: "2024-03-16",
    amount: 85.0,
    category: "Utilities",
    description: "Electricity Bill",
    type: "expense",
    status: "pending",
  },
  {
    id: "tx-6",
    date: "2024-03-15",
    amount: 210.5,
    category: "Shopping",
    description: "Amazon Order",
    type: "expense",
    status: "completed",
  },
  {
    id: "tx-7",
    date: "2024-03-14",
    amount: 500.0,
    category: "Income",
    description: "Freelance Project",
    type: "income",
    status: "completed",
  },
  {
    id: "tx-8",
    date: "2024-03-13",
    amount: 65.0,
    category: "Entertainment",
    description: "Netflix & Spotify",
    type: "expense",
    status: "completed",
  },
  {
    id: "tx-9",
    date: "2024-03-12",
    amount: 25.0,
    category: "Food & Dining",
    description: "Local Bakery",
    type: "expense",
    status: "completed",
  },
  {
    id: "tx-10",
    date: "2024-03-11",
    amount: 400.0,
    category: "Income",
    description: "Dividend Payout",
    type: "income",
    status: "completed",
  },
  {
    id: "tx-11",
    date: "2024-03-10",
    amount: 15.0,
    category: "Health",
    description: "Pharmacy Purchase",
    type: "expense",
    status: "completed",
  },
  {
    id: "tx-12",
    date: "2024-03-09",
    amount: 55.0,
    category: "Transportation",
    description: "Gas Station",
    type: "expense",
    status: "completed",
  },
  {
    id: "tx-13",
    date: "2024-03-08",
    amount: 300.0,
    category: "Electronics",
    description: "Monitor Repair",
    type: "expense",
    status: "completed",
  },
  {
    id: "tx-14",
    date: "2024-03-07",
    amount: 1200.0,
    category: "Income",
    description: "Bonus Payment",
    type: "income",
    status: "completed",
  },
  {
    id: "tx-15",
    date: "2024-03-06",
    amount: 200.0,
    category: "Entertainment",
    description: "Concert Ticket",
    type: "expense",
    status: "completed",
  },
  {
    id: "tx-16",
    date: "2024-03-05",
    amount: 80.0,
    category: "Food & Dining",
    description: "Pizza Dinner",
    type: "expense",
    status: "completed",
  },
  {
    id: "tx-17",
    date: "2024-03-04",
    amount: 45.0,
    category: "Personal Care",
    description: "Haircut",
    type: "expense",
    status: "completed",
  },
  {
    id: "tx-18",
    date: "2024-03-03",
    amount: 110.0,
    category: "Utilities",
    description: "Water Bill",
    type: "expense",
    status: "completed",
  },
  {
    id: "tx-19",
    date: "2024-03-02",
    amount: 900.0,
    category: "Income",
    description: "Rent Income",
    type: "income",
    status: "completed",
  },
  {
    id: "tx-20",
    date: "2024-03-01",
    amount: 180.0,
    category: "Electronics",
    description: "Mechanical Keyboard",
    type: "expense",
    status: "completed",
  },
];
